name: Python CI
on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src   # 👈 agrega /src al path de importación
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q